sudo: false
language: node_js
node_js:
  - 13 
cache: npm
branches:
  only:
    - Source # build master branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  target_branch: master
  on:
    branch: Source
  local-dir: public